---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: dev-namespace
spec:
  chart:
    spec:
      sourceRef:
        namespace: flux-system #Change it if needed     
  values:
    AWX:
      enabled: true
      name: awx-dev
      spec:
        nodeport_port: 30099
        ingress_type: ingress
        hostname: worktestdev.in.net
        ingress_class_name: alb
        ingress_annotations: |
          alb.ingress.kubernetes.io/scheme: "internet-facing"
          alb.ingress.kubernetes.io/target-type: "ip"
          alb.ingress.kubernetes.io/group.name: my-alb-group
          alb.ingress.kubernetes.io/load-balancer-name: my-alb
          alb.ingress.kubernetes.io/actions.ssl-redirect: '443'
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:155386405988:certificate/866611b1-ef9c-4767-ba7b-2cfb2f8bd7d1
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      postgres:
        enabled: true
        host: database-1-instance-1.cqdguar2ilnu.ap-south-1.rds.amazonaws.com
        password: Z22gsjG2eTxy